### ISSUE TITLE
Option to TAB in iPhone. @iphone

### ISSUE THREAD

**Issue by Caedomx** [freeCodeCamp/mobile#1148]
Labels[`keyboard features` `urgent` `new feature]
****Is your feature 
request related to a problem? Please describe.****

_It takes a lot of time away from me because I have to press the space bar so many times to indent my text while coding._

**Describe the solution you'd like**

_Can you PLEASE add a keyboard feature for iPhone users to insert TAB (tabulations) easier while typing_

**Describe alternatives you've considered**
I've thought a bit about it and figured out it would also be an amazing alternative solution to *add a special button somewhere in the UI to get the job done* (in case it was a hassle to mess up with iPhones' keyboards per app).

**Additional context**
I don't know if it's just me but it kind of makes me go desperate when trying to go fast in some topics and lessons to be pressing that button so much (the space bar).

I really thank you and appreciate all  you guys' effort to develop an iOS version of the app and making  it better everyday, 

```[tasklist]
### Tasks
- [ ] https://github.com/freeCodeCamp/mobile/issues/1149
```

```[tasklist]
### Tasks
- [ ] OR add a special button to make TAGS possible
```

hope you take/ my suggestion in consideration seriously!

```[tasklist]
### Tasks
- [ ] Add a draft title or issue reference here
```

```[tasklist]
### Tasks
```

**Comment by Caedomx** [comment]
#iphone
