### ISSUE TITLE
Browse Topics from freeCodeCamp forum

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/mobile#12]
As a user I want to be able to:

- [x] View a lightweight feed from the forum.
- [x] Search for topics on the forum.
- [x] Open topics in a browser window (web-view to OS default browser) - similar behavior to Twitter or Google news apps.

**Comment by Sembauke** [comment]
https://www.figma.com/file/be0h7cYDleGKJwp48Uzx2p/Untitled?node-id=0%3A1
![image](https://user-images.githubusercontent.com/46919888/130052557-9e12c076-273e-4939-b5c7-f50deab0bc5c.png)

**Comment by Sembauke** [comment]
The features here are implemented, tacking further in #37
