### ISSUE TITLE
Browse Articles from freeCodeCamp News

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/mobile#13]
As a user I want to be able to:

- [x] View a lightweight feed from the news.
- [x] Search for topics on the news.
- [x] Save & Bookmark topics offline on device for later use.
- [x] Open topics in a browser window (web-view to OS default browser) - similar behavior to Twitter or Google news apps.

**Comment by Sembauke** [comment]
So I have been working on the mobile newsfeed and I would like to hear your opinions.

Figma has some limitations for animating so certain flows don't work exactly as intended. But there is a fully working prototype of the design.


**The front page:**
1.  The front page has a search bar where users can search for articles.
2.  The front page defines what you are looking at in the header "NEWS FEED"
3.  The articles have a profile picture at the right-top corner with a border with colors issued in the freecodecamp style guide.
4.  The article image has a white border around it so the user can see when a new article begins.
5.  The article has a timestamp when it was published and by who.
6.  The article has a "#" with the subject of the article, when this is clicked it should go to articles with this subject.

This is how the front page looks at the moment:
For a better view [look here](https://www.figma.com/proto/7sESKETT8KmBOZBBlo4mZT/NEWS-WIREFRAME-FREECODECAMP?node-id=1%3A126&scaling=scale-down&page-id=0%3A1&starting-point-node-id=1%3A126&show-proto-sidebar=1)
![image](https://user-images.githubusercontent.com/46919888/126298885-385ff744-3fdc-4f56-9de7-a3a0f1a2b599.png)

The user can  drag the first article down to see if new articles have been published (update feed) 

<a href="https://gyazo.com/15e7ab999ef5243579c4330fe923f40f"><img src="https://i.gyazo.com/15e7ab999ef5243579c4330fe923f40f.gif" alt="Image from Gyazo" width="358"/></a>

The user can click the search icon to search for an article

<a href="https://gyazo.com/4a148f8e202f1cadd901e5ce3e4e7cc4"><img src="https://i.gyazo.com/4a148f8e202f1cadd901e5ce3e4e7cc4.gif" alt="Image from Gyazo" width="354"/></a>

**The article page:** 
1, The article page has the title at the top.
2. The article has a profile picture of the author who wrote it.
3. The article has a bookmark option to read the article at a later time.
4. The article switches back to the front page when the search icon is clicked.
5. You can press the back button in the top left corner.

When the second article title is clicked (For Figma purposes only) the article gets shown to the user.
<a href="https://gyazo.com/a750121e675c2fb300fa84b7bbe1a1b3"><img src="https://i.gyazo.com/a750121e675c2fb300fa84b7bbe1a1b3.gif" alt="Image from Gyazo" width="348"/></a>

An example of the header:
![image](https://user-images.githubusercontent.com/46919888/126302088-ed985f88-1b72-4f15-88a2-94fb53556f4b.png)

The article page is optional, it can also open a web view in a browser.  

This is still a concept and as I said at the top of this message I would like to hear your opinion.
CC: @freeCodeCamp/dev-team, @freeCodeCamp/mobile
