### ISSUE TITLE
[learn] account settings for freeCodeCamp Account

### ISSUE THREAD

**Issue by Sembauke** [freeCodeCamp/mobile#331]
To give the user (when logged-in) full control over their freeCodeCamp account we will need a settings page available.
these settings include:

- [x] Username field
- [x] Name field
- [x] Location field
- [x] Picture
- [x] About

**Privacy**

- [x] My profile - your certifications will be set to private if this is set to private
- [x] My name - if set to private the users name will not be displayed on their certification
- [x] My location - if set to private the users location will not be shown on their profile page.
- [x] My about - if set to private the users about will not be shown on their profile page.
- [x] My points - if set to private the users points will not be shown on their profile page.
- [x] My heatmap - if set to private the users heatmap will not be shown on their profile page
- [x] My certifications - certifications will be disabled if this is set to private

These are the settings (with some exceptions) there is no need to add the functionality of these buttons/fields right away. The most important thing right now will be adding the UI/UX.

**Comment by Rishab-ms** [comment]
Can I work on this?

**Comment by Nirajn2311** [comment]
Sure you can go ahead and get started

**Comment by Sembauke** [comment]
Hey @Rishab-ms,

Good to hear that you want to contribute to the mobile app. 
If you have trouble setting up your development environment, make sure to reach out to us on the official freeCodeCamp Discord server: https://discord.gg/jrBr3sca  or have further questions about this isse.

**Comment by opxdelwin** [comment]
@Sembauke since this [pr](https://github.com/freeCodeCamp/mobile/pull/554) is merged, please do close this issue.

**Comment by Sembauke** [comment]
It was not merged

**Comment by Kavan2003** [comment]
@Sembauke discord link is not not working
