### ISSUE TITLE
forum: functionality, views and authentication

### ISSUE THREAD

**Issue by Sembauke** [freeCodeCamp/mobile#37]
These are functionalities we must/could have that are currently present on the forum.

Steps:
**Authentication:**
- [x] authenticate a user so they can post messages etc.

**Templates:**
- [x] Make a template for making a new message on a post
- [x] Make a template for making a new topic on the forum
- [x] Make a template for viewing an author profile with badges, and other info.
- [x] Make a profile template.
- [x] #49
- [x] Make a settings template

**Functionality:** 

**Topics:**
- [x] Figure out how to send a new message on a topic.
- [x] See in which category the topic was posted.
- [x] Scroll endlessly through topics of a specific category
- [x] Show new comment editor if no comment is present in a post provided the user is logged in

**Author:**
- [x] #53 

**Settings:**

- [x] Change profile picture.
- [x] Change email address.
- [x] Change name.
- [x] Send password reset email.

**Activity:**
- [x] view a list of your posted topics.

**Permissions/ Staff:**
- [x] Give moderator a badge next to their profile image.
- [x] delete, close, edit any posts.
- [x] View hidden topics.

**Optimization:**

**Bugs**
- [x] Emojis are loaded in the original size.
	- <details><summary>Screenshot</summary>
		<img width="316" alt="Screen Shot 2021-10-29 at 13 13 58" src="https://user-images.githubusercontent.com/36357875/139409612-73b255c7-7039-4aa4-801e-2900c72f2cc0.png">
</details>

- [x] The topic close message isn't shown.(This is known to be an issue with the flutter_svg package)
	- <details><summary>Screenshot</summary>
		<img width="1440" alt="Screen Shot 2021-10-29 at 13 53 17" src="https://user-images.githubusercontent.com/36357875/139415017-a9a668d3-e6aa-47f2-86d5-53189b226095.png">
</details>

- [x] Less number of characters warning is improperly positioned and text style buttons always puts cursor to beginning of text.
	- <details><summary>Screenshot</summary>
		<img width="349" alt="Screen Shot 2021-10-29 at 13 50 17" src="https://user-images.githubusercontent.com/36357875/139414613-01d6c114-2ae3-4336-a011-7fa2e19c18c3.png">		
</details>
...
