### ISSUE TITLE
[LEARN] features / UI updates V3.0

### ISSUE THREAD

**Issue by Sembauke** [freeCodeCamp/mobile#449]
## PhoneIDE

- [x] #570
- [x] Make highlighting more accessible by preventing line-breaking (Which would break the highlighting in the entire file) this will make everything more visible.
- [x] An option to select a certain type of language in the code editor which will enable highlighting for that programming language.
- [x] #569

### Required before release
- [x] Gatekeep users if the app is not in latest version

### Updated tasks
- [ ] Update code for forum question creation once freeCodeCamp/freeCodeCamp#47452 is closed
 
#### Header
- [x] It should be possible to view a dropdown which shows all openable files in the current challenge, if there is not more than one file available there should be text instead displaying the file name.
- [x] It should have a preview which displays the current project

#### Instructions Pane - #481
- [x] When starting a new challenge, a pop-up should appear with the current instructions.
- [x] The instructions should close if the user presses a cross icon in the upper-right corner.
- [x] Under the title "Instructions" there should be a progress indicator which displays the number of steps completed and the total number of steps e.g., Step 45 out of 100.

#### Hint Pane
- [x] When a user fails to pass the tests, a pop-up should appear which shows a hint, and indicates what the user needs to do to pass the tests
- [x] The hint should close if the user presses a cross icon in the upper-right corner.
- [x] There should be a button the user can use to reset the challenge
- [x] There should be a button that the user can click to take them to the forum to get external help
- [x] There should be a button to preview the project the user is developing.
- [x] The instructions and hints should cover the same amount of the screen regardless of their content. If the content is larger than the element, it should be scrollable. 

#### Pass Pane
- [x] The pass pane should show up a challenge is completed successfully 
- [x] Inside the past pane there should be a motivational quote 
- [x] The pass pane should have a progress bar that displays the amount completed percent in the current project
- [x] The progress bar should have a text-indicator which displays the number of percent completed
- [ ] The pane should have a share button which implements the ability to make Twitter cards

#### Lower function bar
- [x] There should be a functional bar that includes multiple buttons to execute actions
- [x] There should be a button that hides and opens the instruction pane, when the pane is active the color of the button should change to indicate that the button is active.
- [x] There should be a button to test the challenges.
- [x] The test button should turn green when the challenge passes and indicates that the user can move to the next challenge.
- [x] There should be a button that hides the header which includes the preview and editor dropdown when the user is editing.
- [x] When the user is on the preview pane a button should appear that gives the user the ability to move back to the editor.

### Superblock
- [x]  When a superblock is not available yet there should be a snack-bar which indicates it.

### Block pages
- [x] The user should have the ability to see their progress on the new RWD which has a grid-based challenge layout instead of a list layout (The list layout already has progress indication)
- [x] The block description should not be visible when the block is closed.

**This includes minimal viable product and extra's, this may be discussed publicly. Please if I missed something you would like to see add a comment below.**

---

## Problems and features found/needed in development
This space will be updated with bugs or UI fixes which we come across while making this component

### Features
- [x] When instructions/hint/success panel is open, text and line numbers are not aligned
- [x] Sign in button on pass panel when the user is not signed in
- [x] improve styling for the preview button so that it looks like a toggle button

### Bugs and Flutter errors
- [x] WebView.destroy() called while WebView is still attached to window.
  - [x] This appears when closing a challenge
  - [x] Toggling back to editor from preview
- [x] For a challenge with single file, clicking the editor tab shouldn't refresh the challenge view nor should the user be asked to choose a file. Basically remove the dropdown for single file challenges.

**Comment by ahmadabdolsaheb** [comment]
cc @ahmadabdolsaheb :)

**Comment by ahmadabdolsaheb** [comment]
Thanks for putting this detailed list together. Here are a few points worth mentioning:

- On the success, hint, and instructions states, the editor should shrink and only show one or two lines above and below the active line on the editor. That way the user can select different lines, open the instructions, or hint and compare their answer.
- It might be helpful to think of success, hint, and instructions not as overlays or pop ops since they are placed on the top of the editor rather than covering it (similar to flash messages).
- Initially a line in the editable region is selected.
- The new editor is ideal for the new responsive web design. It would need some changes to be usable for the older and legacy certificates.
- The help and reset button both should show a pop up to confirm the user's intention
- The lower function bar can be shorter on editing mode to open up more space for editing.
- The editor button on the lower function bar of the preview should take the user back to the editor on editing mode where the previous selected line is selected. That button should be displayed when the user is on non editor tab (preview, console, etc). That should save the user a couple of taps.

**Comment by Nirajn2311** [comment]
>  Under the title "Instructions" there should be a progress indicator which displays the number of steps completed and the total number of steps e.g., Step 45 out of 100.

Is this just for the new challenges?

**Comment by ahmadabdolsaheb** [comment]
Yes for now, until we redesign the editor for the older curriculum.

**Comment by Sembauke** [comment]
I think it is fine to do on the old and the new challenges as it's basically the same.

**Comment by ahmadabdolsaheb** [comment]
I agree, I think the design is mainly usable for older challenges but there are a few points to keep in mind for the new RWD.
1) Editable regions notify the editor where to focus.
2) The challenges are shorter 
3) I think the tests are written in order. That is why showing the first failing test would make sense.

If it is a high priority, I will mock the older RWD.

**Comment by Nirajn2311** [comment]
I wouldn't say it's high priority as finishing off the current design would take some time but it would be great to have that also.

**Comment by ahmadabdolsaheb** [comment]
awesome, let's get this in and see the feedback. We could redesign the old RWD accordingly.

**Comment by Nirajn2311** [comment]
> It should be possible to view a dropdown which shows all openable files in the current challenge, if there is not more than one file available there should be text instead displaying the file name.

@ahmadabdolsaheb In the design link, the dropdown text is just `Editors`. If there is multiple files then the text should be the currently shown file right? Also what about the case of one file, will the text be "Editors" or the file?

**Comment by ahmadabdolsaheb** [comment]
So that is an accessibility consideration. Not sure if it applies to mobile. Feel free to look up best practices.
If there is one file, showing the name of the file is fine.

**Comment by Nirajn2311** [comment]
> Pass Pane - The pane should have a share button which implements the ability to make Twitter cards

What exactly should be in the twitter card?

**Comment by ahmadabdolsaheb** [comment]
Good question. This feature needs more research to see what the convention is.  We can initially only show the button when the block is completed and share a link to the block with a meaningful predesigned OG image.

Ultimately we would need to have a dynamic twitter cards similar to https://github.com/freeCodeCamp/freeCodeCamp/issues/47085

Feel free to post pond this feature until we finalize the functionality on the learn repo.

**Comment by ahmadabdolsaheb** [comment]
For the last action item:
- improve styling for the preview button so that it looks like a toggle button.
I think we can keep them as tabs( no toggling)
On the other hand, we can add a contextual button to the code editing view that switches between editing and preview

**Comment by ahmadabdolsaheb** [comment]
<img width="298" alt="Screen Shot 2022-08-11 at 10 32 29 AM" src="https://user-images.githubusercontent.com/4591597/184091639-848b9483-3111-4e72-9e3c-435193bd3954.png">

**Comment by ahmadabdolsaheb** [comment]
Although I am not sure why we would need a toggle at the first place.
1) if users are editing and want to go to preview, they could click on the 'preivew tab'
2) if they want to go from the 'preview tab' to  editing, they could tap on the button the lower navigation

**Comment by ahmadabdolsaheb** [comment]
How about grouping the console and the preview under the `eye` icon since both of those panes are only observable and not editable. That way we could remove the dropdown from the editors tabs and just have them side by side.

That way the lower buttons would be views, but not toggles. Here is a mock, thoughts:
<img width="1429" alt="Screen Shot 2022-08-11 at 11 50 15 AM" src="https://user-images.githubusercontent.com/4591597/184124067-2ae8f655-f350-499f-9e16-2eb6335281ea.png">

**Comment by Sembauke** [comment]
This looks solid Ahmad. If wee keep the amount of files under four it should be good.

**Comment by ahmadabdolsaheb** [comment]
Here is the next iteration
<img width="1101" alt="Screen Shot 2022-08-16 at 4 42 35 PM" src="https://user-images.githubusercontent.com/4591597/184894491-5a2c5ec9-4cf3-405e-98d7-8d998f27aad3.png">
