### ISSUE TITLE
News: functionalities and features

### ISSUE THREAD

**Issue by Sembauke** [freeCodeCamp/mobile#98]
**Author:**
- [x] view an authors page
- [x] view an author bio
- [x] view the articles an author posted
- [x] an picture of the author

**Tags:**
- [x] when clicking on a tag a new feed with that subject should show up
- [x] when clicking the feed it should be clear that the feed is on a certain subject

**Lazy loading:**
- [x] when dragging on the top of the feed it should refresh
- [x] when an article is clicked only a part of the article should be loaded
- [x] a bar that shows how much of the article is left to read

**Styling:**
- [ ] Tables should have the correct color in fcc style
- [x] restyle search

**Bugs:**
- [ ] tables seem to be broken after the lazy-loading update that was implemented.
